defaults:
  - dreamer_v3_XL
  - _self_

#dense_units: 1024
mlp_layers: 6
world_model:
  encoder:
    cnn_channels_multiplier: 128
  recurrent_model:
    recurrent_state_size: 8192
  transition_model:
    hidden_size: 1280
  representation_model:
    hidden_size: 1280