# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_XXL
  - override /env: atari
  - _self_

# Experiment
seed: 6

# Environment
env:
  num_envs: 6
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4
  action_stack: 0
  action_stack_dilation: 1

# Checkpoint
checkpoint:
  every: 10000
  resume_from: /home/sam/dev/sheeprl/logs/runs/dreamer_v3/MsPacmanNoFrameskip-v4/2024-03-31_11-49-33_dreamer_v3_MsPacmanNoFrameskip-v4_6/version_0/checkpoint/ckpt_1200000_0.ckpt

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 10000
  total_steps: 2400000
  train_every: 6
  per_rank_batch_size: 16
  per_rank_sequence_length: 64

fabric:
  precision: 32
