# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: atari
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 6
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4

# Checkpoint
checkpoint:
  every: 2000

# Buffer
buffer:
  size: 600000 # 6*100000=600000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 1024
  total_steps: 600000 # 6*100000=600000
  train_every: 6 # 1*6=6 (dreamer_v3.py:546)
