# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: atari
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 6
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4
  input_buffer: 12
  action_stack: 0

# Checkpoint
checkpoint:
  every: 2000

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 10000
  total_steps: 600000
  train_every: 6
  per_rank_batch_size: 32
  per_rank_sequence_length: 280

fabric:
  precision: 32
