# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: melee
  - _self_

# Experiment
seed: 7

# Environment
env:
  num_envs: 3 # more is not working rn
  max_episode_steps: 6000
  id: melee
  action_stack: 0
  action_stack_dilation: 0
  capture_video: False


# Checkpoint
checkpoint:
  every: 1000
  keep_last: 1
  #resume_from: trained_agent_checkpoint/2024-04-19_18-42-53_dreamer_v3_melee_7/version_0/checkpoint/ckpt_1550000_0.ckpt

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 512
  total_steps: 10000000
  train_every: 3
  per_rank_batch_size: 40
  per_rank_sequence_length: 64
  cnn_keys:
    encoder: [rgb]
    decoder: [rgb]
  mlp_keys:
    encoder: [int_obs_p1, float_obs_p1, int_obs_p2, float_obs_p2, match_completion_ratio]

fabric:
  precision: bf16-true
