# @package _global_

defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_S
  - override /env: atari
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 6
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4
  input_buffer: 30 # noframeskip so try 30 ....old: it already has action repeat to 4 so it should be 3. try with 12 anyway to see

# Checkpoint
checkpoint:
  every: 2000

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 1024
  total_steps: 600000
  train_every: 6
  per_rank_batch_size: 24
