num_threads: 1
float32_matmul_precision: high
dry_run: false
seed: 7
torch_use_deterministic_algorithms: false
torch_backends_cudnn_benchmark: true
torch_backends_cudnn_deterministic: false
cublas_workspace_config: null
exp_name: dreamer_v3_melee
run_name: 2024-04-19_18-42-53_dreamer_v3_melee_7
root_dir: dreamer_v3/melee
algo:
  name: dreamer_v3
  total_steps: 10000000
  per_rank_batch_size: 32
  run_test: true
  cnn_keys:
    encoder: []
    decoder: []
  mlp_keys:
    encoder:
    - one_hot_p1
    - int_obs_p1
    - float_obs_p1
    - one_hot_p2
    - int_obs_p2
    - float_obs_p2
    decoder:
    - one_hot_p1
    - int_obs_p1
    - float_obs_p1
    - one_hot_p2
    - int_obs_p2
    - float_obs_p2
  world_model:
    optimizer:
      _target_: torch.optim.Adam
      lr: 0.0001
      eps: 1.0e-08
      weight_decay: 0
      betas:
      - 0.9
      - 0.999
    discrete_size: 32
    stochastic_size: 32
    kl_dynamic: 0.5
    kl_representation: 0.1
    kl_free_nats: 1.0
    kl_regularizer: 1.0
    continue_scale_factor: 1.0
    clip_gradients: 1000.0
    encoder:
      cnn_channels_multiplier: 96
      cnn_act: torch.nn.SiLU
      dense_act: torch.nn.SiLU
      mlp_layers: 5
      layer_norm: true
      dense_units: 1024
    recurrent_model:
      recurrent_state_size: 4096
      layer_norm: true
      dense_units: 1024
    transition_model:
      hidden_size: 1024
      dense_act: torch.nn.SiLU
      layer_norm: true
    representation_model:
      hidden_size: 1024
      dense_act: torch.nn.SiLU
      layer_norm: true
    observation_model:
      cnn_channels_multiplier: 96
      cnn_act: torch.nn.SiLU
      dense_act: torch.nn.SiLU
      mlp_layers: 5
      layer_norm: true
      dense_units: 1024
    reward_model:
      dense_act: torch.nn.SiLU
      mlp_layers: 5
      layer_norm: true
      dense_units: 1024
      bins: 255
    discount_model:
      learnable: true
      dense_act: torch.nn.SiLU
      mlp_layers: 5
      layer_norm: true
      dense_units: 1024
  actor:
    optimizer:
      _target_: torch.optim.Adam
      lr: 8.0e-05
      eps: 1.0e-05
      weight_decay: 0
      betas:
      - 0.9
      - 0.999
    cls: sheeprl.algos.dreamer_v3.agent.Actor
    ent_coef: 0.0003
    min_std: 0.1
    init_std: 0.0
    objective_mix: 1.0
    dense_act: torch.nn.SiLU
    mlp_layers: 5
    layer_norm: true
    dense_units: 1024
    clip_gradients: 100.0
    expl_amount: 0.0
    expl_min: 0.0
    expl_decay: false
    max_step_expl_decay: 0
    moments:
      decay: 0.99
      max: 1.0
      percentile:
        low: 0.05
        high: 0.95
  critic:
    optimizer:
      _target_: torch.optim.Adam
      lr: 8.0e-05
      eps: 1.0e-05
      weight_decay: 0
      betas:
      - 0.9
      - 0.999
    dense_act: torch.nn.SiLU
    mlp_layers: 5
    layer_norm: true
    dense_units: 1024
    target_network_update_freq: 1
    tau: 0.02
    bins: 255
    clip_gradients: 100.0
  gamma: 0.996996996996997
  lmbda: 0.95
  horizon: 15
  train_every: 1
  learning_starts: 1024
  per_rank_pretrain_steps: 1
  per_rank_gradient_steps: 1
  per_rank_sequence_length: 64
  layer_norm: true
  dense_units: 1024
  mlp_layers: 5
  dense_act: torch.nn.SiLU
  cnn_act: torch.nn.SiLU
  unimix: 0.01
  hafner_initialization: true
  decoupled_rssm: false
  player:
    discrete_size: 32
buffer:
  size: 100000
  memmap: true
  validate_args: false
  from_numpy: false
  checkpoint: true
checkpoint:
  every: 5000
  resume_from: logs/runs/dreamer_v3/melee/2024-04-19_06-58-13_dreamer_v3_melee_7/version_0/checkpoint/ckpt_1455000_0.ckpt
  save_last: true
  keep_last: 1
distribution:
  validate_args: false
  type: auto
env:
  id: melee
  num_envs: 1
  frame_stack: -1
  sync_env: false
  screen_size: 64
  action_repeat: 1
  grayscale: false
  clip_rewards: false
  capture_video: false
  frame_stack_dilation: 1
  max_episode_steps: 6000
  reward_as_observation: false
  wrapper:
    #_target_: sheeprl.envs.melee.MeleeWrapper
    id: melee
    seed: 7
  action_stack: 0
  action_stack_dilation: 0
fabric:
  _target_: lightning.fabric.Fabric
  devices: 1
  num_nodes: 1
  strategy: auto
  accelerator: gpu
  precision: 32
  callbacks:
  - _target_: sheeprl.utils.callback.CheckpointCallback
    keep_last: 5
metric:
  log_every: 5000
  disable_timer: false
  log_level: 1
  sync_on_compute: false
  aggregator:
    _target_: sheeprl.utils.metric.MetricAggregator
    raise_on_missing: false
    metrics:
      Rewards/rew_avg:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Game/ep_len_avg:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/world_model_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/value_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/policy_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/observation_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/reward_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/state_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Loss/continue_loss:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      State/kl:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      State/post_entropy:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      State/prior_entropy:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Params/exploration_amount:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Grads/world_model:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Grads/actor:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
      Grads/critic:
        _target_: torchmetrics.MeanMetric
        sync_on_compute: false
  logger:
    _target_: lightning.fabric.loggers.TensorBoardLogger
    name: 2024-04-19_18-42-53_dreamer_v3_melee_7
    root_dir: logs/runs/dreamer_v3/melee
    version: null
    default_hp_metric: true
    prefix: ''
    sub_dir: null
model_manager:
  disabled: true
  models:
    world_model:
      model_name: dreamer_v3_melee_world_model
      description: DreamerV3 World Model used in melee Environment
      tags: {}
    actor:
      model_name: dreamer_v3_melee_actor
      description: DreamerV3 Actor used in melee Environment
      tags: {}
    critic:
      model_name: dreamer_v3_melee_critic
      description: DreamerV3 Critic used in melee Environment
      tags: {}
    target_critic:
      model_name: dreamer_v3_melee_target_critic
      description: DreamerV3 Target Critic used in melee Environment
      tags: {}
    moments:
      model_name: dreamer_v3_melee_moments
      description: DreamerV3 Moments used in melee Environment
      tags: {}
